Third hw
Neonbird/BI_2019_Python pull request #2
Opened 2019-09-29 21:56 UTC by Neonbird

Сделала оба задания.

2019-10-01 16:24 UTC, AleksandrSl requested changes

2019-10-01 16:24 UTC, AleksandrSl commented on hw3_1.py
> +        if list[i:].count(list[i]) > 1:
А зачем так сложно, почему мы каждый раз ищем в списке,после текущей позиции? Кажется, что мы так пропустим что-то, оно тесты проходит на checkio?

2019-10-01 16:24 UTC, AleksandrSl commented on hw3_2.py
> +    one_dem_l = []
Что значит dem?

2019-10-01 16:24 UTC, AleksandrSl commented on hw3_2.py
> +    for i in array:
i не очень хорошее имя, если это не индекс

2019-10-01 16:24 UTC, AleksandrSl commented on hw3_2.py
> +    return(one_dem_l)
скобки не нужны, PyCharm об этом должен говорить

2019-10-01 16:35 UTC, Neonbird commented on hw3_1.py
> +        if list[i:].count(list[i]) > 1:
Да, тесты проходит. Ничего пропустить не должно. Алгоритм считает кол-во вхождений в список для конкретного элемента. То есть, если на 66-ом месте появилось число, которого до этого не было, то оно посчитает только кол-во его вхождений в промежутке [66:], а в промежутке [1:66] его 100% не было, так что нет смысла пробегаться по списку каждый раз с начала до конца. Я подумала, так будет быстрее работать, если представить, что список большой очень длины.

2019-10-01 16:39 UTC, Neonbird commented on hw3_2.py
> +    one_dem_l = []
Упс, опечатка) должно было быть one_dim_l

> Output data: The one-dimensional list with integers.

2019-10-01 16:41 UTC, Neonbird commented on hw3_2.py
> +    for i in array:
да, я помню с лекций, но было задание уложиться в 140 знаков и я подумала, без разницы, что использовать: '_' , 'n' или 'i'. 'i' как-то привычнее просто.  Но я приняла к сведению)

2019-10-01 17:02 UTC, AleksandrSl commented on hw3_1.py
> +        if list[i:].count(list[i]) > 1:
Ок, звучит неплохо, только ты не учла что операция `[]` копирует список) поэтому у тебя каждый раз создается новая копия списка

2019-10-01 17:02 UTC, AleksandrSl commented on hw3_2.py
> +    one_dem_l = []
Можно и написать `one_dimensional_list`

2019-10-01 17:03 UTC, AleksandrSl commented on hw3_2.py
> +    for i in array:
В 140 не обязательно

2019-10-01 19:44 UTC, Neonbird commented on hw3_1.py
> +        if list[i:].count(list[i]) > 1:
а, т.е. выигрыша никакого? а есть способ ка-то оптимизировать?

2019-10-01 19:55 UTC, Neonbird commented on hw3_2.py
> +    for i in array:
Такое было условие, иначе бы не прошло на checkio, я сокращала, как могла) one_dem_l тоже не  one_dimensional_list по той же причине)

2019-10-01 20:29 UTC, Neonbird commented on hw3_1.py
> +        if list[i:].count(list[i]) > 1:
мб в вариантах решения на checkio есть вариант оптимизации, посмотрю там)

2019-10-01 20:55 UTC, AleksandrSl commented on hw3_1.py
> +        if list[i:].count(list[i]) > 1:
А зачем оптимизировать? Вообще самое нормальное, один раз в начале посчитать все элементы, и потом выбрать те, которые встречаются больше 1 раза

2019-10-01 21:03 UTC, AleksandrSl commented on hw3_2.py
> +    one_dem_l = []
Можно не укладываться в 140, такой ценой

2019-10-01 21:03 UTC, AleksandrSl commented on hw3_2.py
> +    for i in array:
На checkio не проверяется длина)

2019-10-01 21:04 UTC, AleksandrSl approved these changes

2019-10-01 21:07 UTC, AleksandrSl requested changes
![Screenshot from 2019-10-02 00-06-40](https://user-images.githubusercontent.com/15820496/66000738-c0b16280-e4a8-11e9-8855-eaefb4e0a30f.png)

Вот все же как я и думал, он не совсем то будет делать, последние ифры он не берет, так как они встречаются для него один раз

2019-10-01 21:33 UTC, Neonbird commented on hw3_1.py
> +        if list[i:].count(list[i]) > 1:
А, я поняла ошибку свою. 
Ну а оптимизировать, чтобы было)

2019-10-01 21:41 UTC, AleksandrSl requested changes

2019-10-01 21:41 UTC, AleksandrSl commented on hw3_2.py
>          if type(element) == int:
Что-то я просмотрел в прошлый раз, а если тебе внезапно в списке встретится `float` все обвалится, проверять надо на `list` и там реукрсивно вызывать, а так просто все складывать

2019-10-01 21:41 UTC, AleksandrSl commented on hw3_2.py
>          if type(element) == int:
И для проверок типов `is`/`isinstance` https://stackoverflow.com/a/152596/6540091

2019-10-03 18:12 UTC, AleksandrSl approved these changes

2019-10-03 20:31 UTC, merged