Fourth hw
Neonbird/BI_2019_Python pull request #4
Opened 2019-10-28 14:57 UTC by Neonbird

2019-10-30 19:32 UTC, AleksandrSl requested changes

2019-10-30 19:32 UTC, AleksandrSl commented on hw4_1.py
> +    common_words = sorted([word for word in first if first.count(word) > 0 and second.count(word) > 0])
`sorted` принимает любой `iterable`, можно было использовать generator expression
Ну и по поводу сложности тоже вопрос, тут получается n^2 можно за n

2019-10-30 19:32 UTC, AleksandrSl commented on hw4_2.py
> +        if i == 0 or ungrouped[i] != ungrouped[i - 1]:
Интересно, что вы все к такому решению пришли, мне подобный способ ни разу в голову не приходил для подобных задач

2019-10-30 19:32 UTC, AleksandrSl commented on hw4_2.py
> +            grouped_list[j].append(ungrouped[i])
Мы по факту тут всегда добавляем в последний список, в питоне для этого есть очень удобное сокращение в виде отрицательной индексации. Всегда можно просто делать `grouped_list[-1].append(...)`

2019-10-30 19:32 UTC, AleksandrSl commented on hw4_3.py
> +    list_of_int = sorted(list(data))
достаточно `sorted(data)`

2019-10-30 19:32 UTC, AleksandrSl commented on hw4_3.py
> +    intervals = [tuple(interval) for interval in intervals]
Вот в этом примере, если не требуют вернуть именно список можно использовать `map` удобно. `map(tuple, intervals)`

2019-10-30 19:32 UTC, AleksandrSl commented on hw4_3.py
> +        if i == len(list_of_int) - 1 or list_of_int[i] != list_of_int[i + 1] - 1:
Есть ощущение, что тут можно просто `else` поставить, стоит подумать

2019-10-31 08:22 UTC, Neonbird commented on hw4_1.py
> +    common_words = sorted([word for word in first if first.count(word) > 0 and second.count(word) > 0])
Словарём за n?

2019-10-31 09:50 UTC, Neonbird commented on hw4_3.py
> +        if i == len(list_of_int) - 1 or list_of_int[i] != list_of_int[i + 1] - 1:
Если просто `else`, то будут в интервал добавляться не только крайние значения, но и те, кто внутри интервала. А так проверки на то, является ли это значение началом или концом, а средние не учитываются

2019-10-31 09:59 UTC, Neonbird commented on hw4_2.py
> +        if i == 0 or ungrouped[i] != ungrouped[i - 1]:
а какие ещё варианты?

2019-10-31 10:04 UTC, Neonbird commented on hw4_3.py
> +    intervals = [tuple(interval) for interval in intervals]
а вроде и так список возращается, если сделать так)
`intervals = list(map(tuple, intervals))`

2019-10-31 17:52 UTC, AleksandrSl commented on hw4_2.py
> +        if i == 0 or ungrouped[i] != ungrouped[i - 1]:
покажу на паре

2019-10-31 17:53 UTC, AleksandrSl commented on hw4_1.py
> +    common_words = sorted([word for word in first if first.count(word) > 0 and second.count(word) > 0])
Достаточно один из список превратить во множество, и пройтись по второму

2019-10-31 17:54 UTC, AleksandrSl commented on hw4_3.py
> +    intervals = [tuple(interval) for interval in intervals]
Да, если лишний list добавить, то список, но уже не сильно короче становится и не очень красиво

2019-10-31 17:57 UTC, AleksandrSl commented on hw4_1.py
> +    answer = sorted(word for word in common_words if common_words[word] > 1 )
Как я и оветил, достаточно множества)

2019-10-31 17:59 UTC, AleksandrSl requested changes

2019-10-31 17:59 UTC, AleksandrSl commented on hw4_1.py
> +        try:
Так, а это вообще зачем?

2019-10-31 17:59 UTC, AleksandrSl commented on hw4_1.py
> +        try:
А, понял, жесть, не надо так, лучше на самом деле спросить есть ли такой ключ, или использовать `get` метод у словаря

2019-10-31 17:59 UTC, AleksandrSl commented on hw4_3.py
> +        if i == len(list_of_int) - 1 or list_of_int[i] != list_of_int[i + 1] - 1:
Можно это на самом деле обойти, на паре посмотрим)

2019-10-31 18:51 UTC, Neonbird commented on hw4_1.py
> +        try:
поч не надо?)

2019-10-31 18:51 UTC, Neonbird commented
И я не пойму на чём травис валится(

2019-10-31 19:01 UTC, AleksandrSl commented on hw4_1.py
> +        try:
на паре еще раз скажу, уже как-то говорил, я тут преисполнился вам уже одинаковвые комментарии писать)

2019-10-31 19:02 UTC, AleksandrSl commented
`./hw4_1.py:8:9: E722 do not use bare 'except'`
вот на этом, там же написано)

2019-11-05 20:46 UTC, merged